-- Online PvP backend for Mini Kingdom.
-- Run this in the Supabase SQL editor, then set VITE_SUPABASE_URL and
-- VITE_SUPABASE_ANON_KEY in .env (Project Settings -> API).

create table if not exists public.villages (
    id text primary key,                 -- playerId generated by the client
    name text not null,
    trophies integer not null default 0,
    shield_until timestamptz not null default now(),
    snapshot jsonb not null,             -- garrison, defense god, walls, lootable coins...
    updated_at timestamptz not null default now()
);

create index if not exists villages_trophies_idx on public.villages (trophies);

create table if not exists public.attacks (
    id text primary key,
    attacker_id text not null,
    defender_id text not null references public.villages (id) on delete cascade,
    record jsonb not null,               -- result shown to the defender
    created_at timestamptz not null default now()
);

create index if not exists attacks_defender_idx on public.attacks (defender_id, created_at);

-- Row Level Security: anyone with the anon key can read villages and
-- publish/attack. This is fine for a prototype; see README for hardening
-- (Supabase Auth + validating battles in an Edge Function).
alter table public.villages enable row level security;
alter table public.attacks enable row level security;

create policy "villages are public" on public.villages for select using (true);
create policy "players publish their village" on public.villages for insert with check (true);
create policy "players update their village" on public.villages for update using (true);

create policy "defenders read attacks" on public.attacks for select using (true);
create policy "attackers report attacks" on public.attacks for insert with check (true);

-- Cloud Saves for logged in users
create table if not exists public.player_saves (
    user_id uuid primary key references auth.users (id) on delete cascade,
    player_id text not null,
    game_state jsonb not null,
    updated_at timestamptz not null default now()
);

alter table public.player_saves enable row level security;

create policy "users manage their own cloud save"
on public.player_saves
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

